### ISSUE TITLE
Creating multiple monitored items in one request

### ISSUE THREAD

**Issue by oliver** [open62541pp/open62541pp#185]
So far I have used `Subscription::subscribeDataChange()` to add a `MonitoredItem` for a variable. But I want to monitor quite a lot of variables (about 200), which is slow due to the many request-response roundtrips.

It looks like the `UA_Client_MonitoredItems_createDataChanges()` function could solve this, by setting up lots of monitorings in one request. But it looks like there is not yet a C++ wrapper for this function in open62541pp, right?

Are there plans to add a C++ wrapper for `UA_Client_MonitoredItems_createDataChanges()`? Or should this problem rather be solved by starting lots of async requests in parallel (using e.g. the implementation from https://github.com/open62541pp/open62541pp/pull/111)?

Btw. thanks for the "groundwork" provided in open62541pp – for testing I have called `UA_Client_MonitoredItems_createDataChanges()` manually, and the wrappers from the C++ library were really helpful for that!

**Comment by lukasberbuer** [comment]
Hi @oliver,
this is definitely on the roadmap for the near future.
The initial goal of open62541pp was to expose symmetric interfaces for both server and client. The open62541 API doesn't allow to create multiple monitored items / subscriptions on the server-side. But lately, the raw client services have been exposed in the `services` namespace.
