### ISSUE TITLE
Trusting certificates runtime

### ISSUE THREAD

**Issue by notzain** [open62541pp/open62541pp#311]
I am starting a server with server certificates using the example code from https://github.com/open62541pp/open62541pp/blob/52efa1f36a6ab6b51c049ef2d58b51fd8a716128/tests/Crypto.cpp#L93

Using an OPCUA client I can confirm the encryption is recognized. However, opening an encryption connection will result in `BadCertificateUntrusted` on the server. This makes sense, as the trust list given to the server was an empty array. Is there a way to get a hold of the untrusted certificate and trust it at runtime?

**Comment by lukasberbuer** [comment]
Hi @notzain,

this is handled by the `UA_CertificateVerification` plugin: https://github.com/open62541/open62541/blob/v1.3.12/include/open62541/plugin/pki.h#L35-L49

The server stores an instance of `UA_CertificateVerification` in its config `UA_ServerConfig` and can be overwritten with a custom logic: https://github.com/open62541/open62541/blob/v1.3.12/include/open62541/server.h#L172

```cpp
opcua::Server server;
auto* config = UA_Server_getConfig(server.handle());
config->certificateVerification = createMyCustomCertificateVerification();
```

You can get some ideas from the default implementation (which is depending on the crypto library you are using). Here you see the trustlist implementation for mbedtls: https://github.com/open62541/open62541/blob/v1.3.12/plugins/crypto/mbedtls/ua_pki_mbedtls.c#L519-L576
