### ISSUE TITLE
Subscribing to an event of a variable node

### ISSUE THREAD

**Issue by CuongNguyen-Emotiv** [open62541pp/open62541pp#313]
I am using `Prosys OPC UA Simulation Server`. 
In the event view of the UaExpert client I can drag and drop a variable node and subscribe to an event of this node.

![image](https://github.com/user-attachments/assets/48b9d84f-5a49-4294-a75a-106e9e37a08c)

How can I do the same on my server?
Is there any sample code to do this?

**Comment by lukasberbuer** [comment]
Hi @CuongNguyen-Emotiv, did you have a look at the examples?
https://github.com/open62541pp/open62541pp/tree/master/examples/events

To understand the events model in more detail, I recommend to read following chapter in the standard: https://reference.opcfoundation.org/Core/Part3/v105/docs/4.7

**Comment by lukasberbuer** [comment]
Please reopen or create new issue if you have further questions.
