### ISSUE TITLE
Add library version information

### ISSUE THREAD

**Issue by ErikTempelaarVO** [open62541pp/open62541pp#315]
Our app has the ability to show the libraries it makes use of and I would like to add open62541pp to that output.

```
    spdlog::info("{} open62541 library: v{} with {}", APP_NAME, UA_OPEN62541_VER_COMMIT, OPENSSL_VERSION_TEXT);
    spdlog::info("{} CPR library      : v{}", APP_NAME, CPR_VERSION);
```

> my_app open62541 library: v1.3.4 with OpenSSL 3.1.3 19 Sep 2023
> my_app CPR library      : v1.10.5

Would you consider adding/generating these "macros" and make them available in some kind of "version"-headerfile?

**Comment by lukasberbuer** [comment]
Hi @ErikTempelaarVO, just implemented this in PR #316. Please review.
