### ISSUE TITLE
Simplify Variant copy getters?

### ISSUE THREAD

**Issue by lukasberbuer** [open62541pp/open62541pp#491]
Now having the unified constructor for `Variant` (#384), it would be great to have a unified getter that supports both value kinds (scalar/array) and conversions to non-native types. @chandryan and I already discussed a `getValue` getter.

Status quo:
```cpp
opcua::Variant var("test123");
auto& native = var.scalar<opcua::String>();  // get scalar by reference
auto str = var.scalarCopy<std::string>();  // get scalar by copy and perform conversions (if needed)
```

The unified constructor uses a logic to distinguish between scalars and arrays objects. The same logic could be used in a getter by providing the target type as a template parameter:
- Return scalar if the template type is a registered or convertible type.
- Return container of given type if the template type is a container with a registered or convertible type. The container should be constructible from an iterator pair.

This getter could just be called `Variant::to<T>()`:

```cpp
opcua::Variant varScalar("test123");
auto str = varScalar.to<std::string>();

std::vector<int> array{1, 2, 3};
opcua::Variant varArray(array);
auto lst = varArray.to<std::list<int>>();
auto vec = varArray.to<std::vector<int>>();
```

Any ideas? @chandryan what's your take on this?

**Comment by chandryan** [comment]
> Now having the unified constructor for `Variant` (#384), it would be great to have a unified getter that supports both value kinds (scalar/array) and conversions to non-native types. @chandryan and I already discussed a `getValue` getter.
> 
> Status quo:
> 
> ```c++
> opcua::Variant var("test123");
> auto& native = var.scalar<opcua::String>();  // get scalar by reference
> auto str = var.scalarCopy<std::string>();  // get scalar by copy and perform conversions (if needed)
> ```
> 
> The unified constructor uses a logic to distinguish between scalars and arrays objects. The same logic could be used in a getter by providing the target type as a template parameter:
> 
> * Return scalar if the template type is a registered or convertible type.
> * Return container of given type if the template type is a container with a registered or convertible type. The container should be constructible from an iterator pair.
> 
> This getter could just be called `Variant::to<T>()`:
> 
> ```c++
> opcua::Variant varScalar("test123");
> auto str = varScalar.to<std::string>();
> 
> std::vector<int> array{1, 2, 3};
> opcua::Variant varArray(array);
> auto lst = varArray.to<std::list<int>>();
> auto vec = varArray.to<std::vector<int>>();
> ```
> 
> Any ideas? @chandryan what's your take on this?

I like the expressiveness of a `Variant::to<T>` over `Variant::value<T>()`, good idea! 👍
