### ISSUE TITLE
Question about nullptr input in the Variant's "no copy" APIs

### ISSUE THREAD

**Issue by chandryan** [open62541pp/open62541pp#509]
Hi @lukasberbuer,

the new Variant interface looks really slick, great work!! 😎 

I have a minor remark about the `nullptr` edge case that is currently used in the `Variant`'s `assign` functions as well as in the `ExtensionObject` constructor:

In the `ExtensionObject`'s constructor I think it makes sense to early-return with an effectively default-constructed object, though in the context of `Variant`'s assignment I find this behavior contra-intuitive. My expectation would be that a nullptr assignment resets the Variant, so that it's empty again. Similar to e.g. resetting a `std::function myFunction` via `myFunction = nullptr;`.

What do you think?

**Comment by lukasberbuer** [comment]
Thank you @chandryan. It's all based on your work 😊
I totally agree, passing a `nullptr` to `Variant::assign` should clear the variant.

Do you want to provide a PR?
