### ISSUE TITLE
Basic256Sha256 Support

### ISSUE THREAD

**Issue by joshzoi** [open62541pp/open62541pp#60]
Hi all,

First of all, awesome work with this library, thanks for sharing!

I want to ask if there is any plan to include support for security policies, such as **Basic256Sha256**? This would be great as currently security must be disabled server-side for this OPCUA client to successfully connect.

Thanks 😄

**Comment by lukasberbuer** [comment]
Hi @joshzoi, thanks for the nice words 😃
This feature is on my list for a long time. I would like to combine this with #34 to avoid overloading both the `Client` and `Server` class. I will provide some drafts the next days and hopefully finalize it together this week.
